In [1]:
#HW3

In [2]:
#Problem2

In [3]:
#a

In [4]:
import pandas as pd
import numpy as np

In [5]:
yelp_df = pd.read_csv("yelp_labelled.txt", sep='\t', header=None)
print(yelp_df.shape)
print(yelp_df[1].value_counts())
amazon_df = pd.read_csv("amazon_cells_labelled.txt", sep='\t', header=None)
print(amazon_df.shape)
print(amazon_df[1].value_counts())

(1000, 2)
1    500
0    500
Name: 1, dtype: int64
(1000, 2)
1    500
0    500
Name: 1, dtype: int64


In [6]:
# This fails with (748,2) instead of (1000,2)
#imdb_df = pd.read_table("imdb_labelled.txt", sep='\t', header=None, 
#                      encoding='utf_8',verbose=True)
#print(imdb_df.shape)

# using readlines()
count = 0 
text_list = []
score_list = []
with open("imdb_labelled.txt") as txt_file:
    lines = txt_file.readlines()
    for line in lines:
        split_line = line.split('\t')
        text_list.append(split_line[0])
        score_list.append(split_line[1])
        count += 1
print(count)
print(len(text_list))
print(len(score_list))

1000
1000
1000


In [7]:
print(line)

All in all its an insult to one's intelligence and a huge waste of money.  	0



In [8]:
#Labels are all perfectly balanced for all files. 500:500 for each
#file. 1:1. 
#I processed the files via Pandas and Python readlines. 

In [9]:
#b

In [10]:
import re
from collections import defaultdict
#import nltk

STOPWORDS_SET = {'ourselves', 'hers', 'between', 'yourself', 'but', 'again', 'there', 'about', 'once',
                 'during', 'out', 'very', 'having', 'with', 'they', 'own', 'an', 'be', 'some', 'for',
                 'do', 'its', 'yours', 'such', 'into', 'of', 'most', 'itself', 'other', 'off', 'is', 's',
                 'am', 'or', 'who', 'as', 'from', 'him', 'each', 'the', 'themselves', 'until', 'below',
                 'are', 'we', 'these', 'your', 'his', 'through', 'don', 'nor', 'me', 'were', 'her', 'more',
                 'himself', 'this', 'down', 'should', 'our', 'their', 'while', 'above', 'both', 'up', 'to',
                 'ours', 'had', 'she', 'all', 'no', 'when', 'at', 'any', 'before', 'them', 'same', 'and',
                 'been', 'have', 'in', 'will', 'on', 'does', 'yourselves', 'then', 'that', 'because', 'what',
                 'over', 'why', 'so', 'can', 'did', 'not', 'now', 'under', 'he', 'you', 'herself', 'has',
                 'just', 'where', 'too', 'only', 'myself', 'which', 'those', 'i', 'after', 'few', 'whom',
                 't', 'being', 'if', 'theirs', 'my', 'against', 'a', 'by', 'doing', 'it', 'how', 'further',
                 'was', 'here', 'than',''}
TUP_FLAG = 1
def preprocess_text(input_text):
    """
    Args: input_text (str)
    Returns: word_count (defaultdict)
    """
    # Lowercase all letters because dataset size is only 3000.
    input_text = input_text.lower()
    
    # Do not lmennatization because we will use 2 tuples later.
    # Strip punctuation because of often repeated !!!
    input_text = re.sub(r'[^\w\s]', '', input_text)
    
    # Take out stop words because we aren't using TFIDF here
    # Might mess up 2 tuple ngram model later
    wc_dict = defaultdict(int)
    split_text = input_text.split(' ')
    if not TUP_FLAG:
        for word in split_text:
            if word not in STOPWORDS_SET:
                wc_dict[word] += 1
    else:
        filtered_words = [word for word in split_text if word not in STOPWORDS_SET]
        if len(filtered_words) < 2:
            return wc_dict
        else:          
            for i in range(len(filtered_words)-1):
                word = filtered_words[i] + '_' + filtered_words[i+1]
                wc_dict[word] += 1
    return wc_dict

tmp = preprocess_text('asdfASDF.! whatever, ourselves, do its and, so any them before, hello how are you')
print(tmp)

defaultdict(<class 'int'>, {'asdfasdf_whatever': 1, 'whatever_hello': 1})


In [11]:
#c

In [12]:
# This fails with (748,2) instead of (1000,2)
#imdb_df = pd.read_table("./sentiment labelled sentences/imdb_labelled.txt", sep='\t', header=None, 
#                      encoding='utf_8',verbose=True)
#print(imdb_df.shape)
TUP_FLAG = 0
# using readlines()


def nlp_train_test_split(file_name="imdb_labelled.txt"):
    count = 0 
    pos_count = 0
    neg_count = 0
    train_text_list = []
    train_score_list = []
    test_text_list = []
    test_score_list = []
    with open(file_name) as txt_file:
        lines = txt_file.readlines()
        for line in lines:
            count += 1
            split_line = line.split('\t')
            target_val = int(split_line[1])
            text_val = preprocess_text(split_line[0])
            if target_val == 0:
                neg_count +=1 
            else:
                pos_count +=1         
            if target_val == 0 and neg_count <= 400:
                train_score_list.append(target_val)
                train_text_list.append(text_val)
            elif target_val == 1 and pos_count <= 400:
                train_score_list.append(target_val)
                train_text_list.append(text_val)
            elif target_val == 0 and neg_count > 400:
                test_score_list.append(target_val)
                test_text_list.append(text_val)            
            elif target_val == 1 and pos_count > 400:
                test_score_list.append(target_val)
                test_text_list.append(text_val)    
    return train_text_list, train_score_list, test_text_list, test_score_list




In [13]:
file_list = ["imdb_labelled.txt",
             "yelp_labelled.txt",
             "amazon_cells_labelled.txt",
            ]
train_text_list = []
train_score_list = []
test_text_list = []
test_score_list = []
for file_name in file_list:
    tr1,tr2, te1, te2 = nlp_train_test_split(file_name)
    train_text_list += tr1
    train_score_list += tr2
    test_text_list += te1
    test_score_list += te2
    
print('done')
    

done


In [14]:
print(len(train_text_list))
print(len(test_text_list))
print(len(train_score_list))
print(len(test_score_list))

print(pd.Series(train_score_list).value_counts())
print(pd.Series(test_score_list).value_counts())

2400
600
2400
600
1    1200
0    1200
dtype: int64
1    300
0    300
dtype: int64


In [15]:
train_text_list[0:5]

[defaultdict(int,
             {'slowmoving': 1,
              'aimless': 1,
              'movie': 1,
              'distressed': 1,
              'drifting': 1,
              'young': 1,
              'man': 1}),
 defaultdict(int,
             {'sure': 1,
              'lost': 1,
              'flat': 1,
              'characters': 1,
              'audience': 1,
              'nearly': 1,
              'half': 1,
              'walked': 1}),
 defaultdict(int,
             {'attempting': 1,
              'artiness': 1,
              'black': 1,
              'white': 1,
              'clever': 1,
              'camera': 1,
              'angles': 1,
              'movie': 1,
              'disappointed': 1,
              'became': 1,
              'even': 1,
              'ridiculous': 1,
              'acting': 1,
              'poor': 1,
              'plot': 1,
              'lines': 1,
              'almost': 1,
              'nonexistent': 1}),
 defaultdict(int, {'little': 1, 'm

In [16]:
#d

In [17]:
train_text_list[-2:]

[defaultdict(int, {'awkward': 1, 'use': 1, 'unreliable': 1}),
 defaultdict(int, {'good': 1, 'hoped': 1})]

In [18]:
vocabulary_dict = defaultdict(int)

for d in train_text_list:
    for k,v in d.items():
        vocabulary_dict[k] += v

print(len(vocabulary_dict))

4590


In [19]:
#You can't use test at the start because in production ML you don't
#have access to future data (e.g. test)
#Therefore your model can't access the future word counts in test.
#These are unknown in production. 

In [20]:
#e

In [21]:
import scipy.sparse as sp
import hashlib 

hash_word_dict = {}
MAX_COLUMNS = 99999 #2147483646 # possible hash collisions
data_list = []
row_ind_list = []
col_ind_list = []

for i,d in enumerate(train_text_list):
    for k,v in d.items():
        row_ind_list.append(i)
        data_list.append(np.log1p(v))
        val = int(hashlib.sha256(k.encode()).hexdigest(),16) % MAX_COLUMNS
        hash_word_dict[val] = k
        col_ind_list.append(val)
#You can create csr_matrix at once (like this format: csr_matrix((data, (row_ind, col_ind))). 
X_train = sp.csr_matrix((data_list, (row_ind_list, col_ind_list))) # sparse csr matrix
X_train

<2400x99967 sparse matrix of type '<class 'numpy.float64'>'
	with 14586 stored elements in Compressed Sparse Row format>

In [22]:
MAX_COLUMNS = 99999 #2147483646
data_list = []
row_ind_list = []
col_ind_list = []

for i,d in enumerate(test_text_list):
    for k,v in d.items():
        if vocabulary_dict[k] > 0:
            row_ind_list.append(i)
            data_list.append(np.log1p(v))
            val = int(hashlib.sha256(k.encode()).hexdigest(),16) % MAX_COLUMNS
            col_ind_list.append(val)
#You can create csr_matrix at once (like this format: csr_matrix((data, (row_ind, col_ind))). 
X_test = sp.csr_matrix((data_list, (row_ind_list, col_ind_list))) # sparse csr matrix
X_test

<600x99967 sparse matrix of type '<class 'numpy.float64'>'
	with 2957 stored elements in Compressed Sparse Row format>

In [23]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB(alpha=0.000001)
clf.fit(X_train, train_score_list)
preds = clf.predict(X_test)
preds.shape

(600,)

In [24]:
from sklearn.metrics import confusion_matrix
cm_val =  confusion_matrix(test_score_list, preds)
cm_val

array([[247,  53],
       [ 81, 219]])

In [25]:
def my_naive_bayes():
    """
    Scipy implementation of MultinomialNB with equal class distribution assumed. 
    Our example in the HW2 has equal class distribution 1:1
    """
    y = sp.csr_matrix(([1]*len(train_score_list), (list(range(len(train_score_list))),
                                           train_score_list)))

    feature_count = y.T.dot(X_train)
    preds =  feature_count.dot(X_test.T)
    
    # If class distribution was not 1:1
    #print(preds.shape)
    mean_val = np.mean(train_score_list)
    if mean_val != 0.5:
        class_prior = np.vstack((np.array([1-mean_val]*preds.shape[1]),
                                np.array([mean_val]*preds.shape[1])))
        #print(class_prior.shape)
        preds += np.log1p(class_prior.reshape(2,-1))
    
    
    preds = np.argmax(preds, axis=0)
    return preds.tolist()[0]

preds = my_naive_bayes()
preds[0:10]

[0, 0, 1, 0, 1, 0, 1, 1, 1, 0]

In [26]:
#I will use log-normalization because of the sparseness of the data.
#I want to Laplace smooth the counts for naive bayes.

In [27]:
#f

In [28]:
cm_val =  confusion_matrix(test_score_list, preds)
cm_val

array([[226,  74],
       [ 72, 228]])

In [29]:
# MyNaiveBayes Test accuracy of 0.75666666666667
np.sum(np.array(test_score_list)== np.array(preds))/len(preds)

0.7566666666666667

In [30]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(penalty='elasticnet',l1_ratio=0.5, solver='saga')
clf.fit(X_train, train_score_list)
preds = clf.predict(X_test)
print(np.sum(np.array(test_score_list)== np.array(preds))/len(preds))
#0.7883333333333333
cm_val =  confusion_matrix(test_score_list, preds)
cm_val

0.79


array([[261,  39],
       [ 87, 213]])

In [31]:
hash_word_dict[np.argmax(clf.coef_)]

'great'

In [32]:
hash_word_dict[np.argmin(clf.coef_)]

'bad'

In [33]:
# Positive words such as great make a label great, Negative words such
#as bad make a label bad. 

In [34]:
"""
array([[226,  74],
       [ 72, 228]])
Test Accuracy 0.7566666666666667
"""

'\narray([[226,  74],\n       [ 72, 228]])\nTest Accuracy 0.7583333333333333\n'

In [36]:
#h

In [37]:
TUP_FLAG = 1



def nlp_train_test_split(file_name="imdb_labelled.txt"):
    count = 0 
    pos_count = 0
    neg_count = 0
    train_text_list = []
    train_score_list = []
    test_text_list = []
    test_score_list = []
    with open(file_name) as txt_file:
        lines = txt_file.readlines()
        for line in lines:
            count += 1
            split_line = line.split('\t')
            target_val = int(split_line[1])
            text_val = preprocess_text(split_line[0])
            if target_val == 0:
                neg_count +=1 
            else:
                pos_count +=1         
            if target_val == 0 and neg_count <= 400:
                train_score_list.append(target_val)
                train_text_list.append(text_val)
            elif target_val == 1 and pos_count <= 400:
                train_score_list.append(target_val)
                train_text_list.append(text_val)
            elif target_val == 0 and neg_count > 400:
                test_score_list.append(target_val)
                test_text_list.append(text_val)            
            elif target_val == 1 and pos_count > 400:
                test_score_list.append(target_val)
                test_text_list.append(text_val)    
    return train_text_list, train_score_list, test_text_list, test_score_list




In [38]:
file_list = ["imdb_labelled.txt",
             "yelp_labelled.txt",
             "amazon_cells_labelled.txt",
            ]
train_text_list = []
train_score_list = []
test_text_list = []
test_score_list = []
for file_name in file_list:
    tr1,tr2, te1, te2 = nlp_train_test_split(file_name)
    train_text_list += tr1
    train_score_list += tr2
    test_text_list += te1
    test_score_list += te2
    
print('done')

done


In [39]:
print(len(train_text_list))
print(len(test_text_list))
print(len(train_score_list))
print(len(test_score_list))

print(pd.Series(train_score_list).value_counts())
print(pd.Series(test_score_list).value_counts())

2400
600
2400
600
1    1200
0    1200
dtype: int64
1    300
0    300
dtype: int64


In [40]:
train_text_list[0:5]

[defaultdict(int,
             {'slowmoving_aimless': 1,
              'aimless_movie': 1,
              'movie_distressed': 1,
              'distressed_drifting': 1,
              'drifting_young': 1,
              'young_man': 1}),
 defaultdict(int,
             {'sure_lost': 1,
              'lost_flat': 1,
              'flat_characters': 1,
              'characters_audience': 1,
              'audience_nearly': 1,
              'nearly_half': 1,
              'half_walked': 1}),
 defaultdict(int,
             {'attempting_artiness': 1,
              'artiness_black': 1,
              'black_white': 1,
              'white_clever': 1,
              'clever_camera': 1,
              'camera_angles': 1,
              'angles_movie': 1,
              'movie_disappointed': 1,
              'disappointed_became': 1,
              'became_even': 1,
              'even_ridiculous': 1,
              'ridiculous_acting': 1,
              'acting_poor': 1,
              'poor_plot': 1,
   

In [41]:
"""
You can't use test at the start because in production ML you don't have access to future data (e.g. test)
Therefore your model can't access the future word counts in test. These are unknown in production. 
"""

"\nYou can't use test at the start because in production ML you don't have access to future data (e.g. test)\nTherefore your model can't access the future word counts in test. These are unknown in production. \n"

In [42]:
train_text_list[-2:]

[defaultdict(int, {'awkward_use': 1, 'use_unreliable': 1}),
 defaultdict(int, {'good_hoped': 1})]

In [43]:
vocabulary_dict = defaultdict(int)

for d in train_text_list:
    for k,v in d.items():
        vocabulary_dict[k] += v

print(len(vocabulary_dict))

11444


In [ ]:
"""
I will use log-normalization because of the sparseness of the data.
I want to Laplace smooth the counts for naive bayes.
"""

In [44]:
import scipy.sparse as sp
import hashlib 

hash_word_dict = {}
MAX_COLUMNS = 13000 # 22430 #9999 #2147483646 # possible hash collisions
data_list = []
row_ind_list = []
col_ind_list = []

for i,d in enumerate(train_text_list):
    for k,v in d.items():
        row_ind_list.append(i)
        data_list.append(np.log1p(v))
        val = int(hashlib.sha512(k.encode()).hexdigest(),16) % MAX_COLUMNS
        hash_word_dict[val] = k
        col_ind_list.append(val)
#You can create csr_matrix at once (like this format: csr_matrix((data, (row_ind, col_ind))). 
X_train = sp.csr_matrix((data_list, (row_ind_list, col_ind_list))) # sparse csr matrix
X_train

<2400x13000 sparse matrix of type '<class 'numpy.float64'>'
	with 12423 stored elements in Compressed Sparse Row format>

In [45]:
MAX_COLUMNS = 13000 
data_list = []
row_ind_list = []
col_ind_list = []

for i,d in enumerate(test_text_list):
    for k,v in d.items():
        if vocabulary_dict[k] > 0:
            row_ind_list.append(i)
            data_list.append(np.log1p(v))
            val = int(hashlib.sha512(k.encode()).hexdigest(),16) % MAX_COLUMNS
            col_ind_list.append(val)
#You can create csr_matrix at once (like this format: csr_matrix((data, (row_ind, col_ind))). 
X_test = sp.csr_matrix((data_list, (row_ind_list, col_ind_list))) # sparse csr matrix
X_test = sp.csr_matrix((X_test.data, X_test.indices, X_test.indptr), shape=(600, MAX_COLUMNS))
X_test

<600x13000 sparse matrix of type '<class 'numpy.float64'>'
	with 347 stored elements in Compressed Sparse Row format>

In [46]:
from sklearn.naive_bayes import MultinomialNB

# The difference between MultinomialNB and my_naive_bayes is 
# that sklearn will np.log1p again within its MultinomialNB
# I only np.log1p once in preprocessing
clf = MultinomialNB(alpha=0.00000001)
clf.fit(X_train, train_score_list)
preds = clf.predict(X_test)
preds.shape

(600,)

In [47]:
from sklearn.metrics import confusion_matrix
cm_val =  confusion_matrix(test_score_list, preds)
cm_val

array([[271,  29],
       [205,  95]])

In [48]:
#self.feature_count_ += safe_sparse_dot(Y.T, X)

#afe_sparse_dot(X, self.feature_log_prob_.T) 
def my_naive_bayes():
    """
    Scipy implementation of MultinomialNB with equal class distribution assumed. 
    Our example in the HW2 has equal class distribution 1:1
    """
    y = sp.csr_matrix(([1]*len(train_score_list), (list(range(len(train_score_list))),
                                           train_score_list)))

    feature_count = y.T.dot(X_train)
    preds =  feature_count.dot(X_test.T)
    
    # If class distribution was not 1:1
    #print(preds.shape)
    mean_val = np.mean(train_score_list)
    if mean_val != 0.5:
        class_prior = np.vstack((np.array([1-mean_val]*preds.shape[1]),
                                np.array([mean_val]*preds.shape[1])))
        #print(class_prior.shape)
        preds += np.log1p(class_prior.reshape(2,-1))
    
    
    preds = np.argmax(preds, axis=0)
    return preds.tolist()[0]

preds = my_naive_bayes()
preds[0:10]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [49]:
cm_val =  confusion_matrix(test_score_list, preds)
cm_val

array([[272,  28],
       [206,  94]])

In [50]:
# MyNaiveBayes Test accuracy of 0.61
np.sum(np.array(test_score_list)== np.array(preds))/len(preds)

0.61

In [51]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(penalty='elasticnet',l1_ratio=0.5, solver='saga')
clf.fit(X_train, train_score_list)
preds = clf.predict(X_test)
print(np.sum(np.array(test_score_list)== np.array(preds))/len(preds))
#0.5733333333333334
cm_val =  confusion_matrix(test_score_list, preds)
cm_val

0.5733333333333334


array([[285,  15],
       [241,  59]])

In [52]:
#'works_great'
hash_word_dict[np.argmax(clf.coef_)]

'works_great'

In [53]:
#'waste_time'
hash_word_dict[np.argmin(clf.coef_)]

'waste_time'

In [54]:
# Positive tuples like works_great make a label great, Negative phrases such as waste_time make a label bad. 

In [55]:
#i

In [56]:
"""
Logistic Regression Elasticnet l1 ratio 0.5 performs the best with 1-grams. 
It appears 2-grams are worse given the small data row size. 
Positive words and phrases make a online review positive. Great.
Negative words and phrases make a online review negative. Bad. Waste.
"""

'\nLogistic Regression Elasticnet l1 ratio 0.5 performs the best with 1-grams. \nIt appears 2-grams are worse given the small data row size. \nPositive words and phrases make a online review positive. Great.\nNegative words and phrases make a online review negative. Bad. Waste.\n'